### ISSUE TITLE
FROM故障時のダウンリンクモードを作ったほうが良いのか？

### ISSUE THREAD

**Issue by ryogaide** [OrigamiSat1Project/PIC_5R8G#3]
現状はOBCからUART貰った画像binaryデータを逐一FROMに保存して画像保存を行っている。
その後OBCからダウンリンク指令を受けてFROMに保存されている画像をダウンリンクする仕様。
しかし、宇宙空間上でFROMが故障した場合の冗長システムが組めていない。
FROMが故障した場合PIC内のバッファで対応せざるを得ないが、その動作モードを作る必要があるのか？
その場合PIC内のバッファがフルになるたびにアンプの電源ON・OFFを繰り返し、動作モードとしてはかなりロスが多くなりそう。

**Comment by reokashiyama** [comment]
俺個人的な意見としては，今開発ギリギリだからFROM故障時はあきらめる，でよいのではないかと考えます．

結局将来運用時の選択肢として残すのかどうかだと思う．
たぶんVHFでダウンリンクしたほうが楽だと思うけど，選択肢としてそういうモードを作るかどうかだと思う．
余裕があったらそういう動作モード作っても良いけど，今の余裕的にはなさそうだな
FM開発リミット5月中だし
