### ISSUE TITLE
一度に40byte以上送ると、どこかのループに入ってしまうバグ

### ISSUE THREAD

**Issue by ryogaide** [OrigamiSat1Project/PIC_5R8G#6]
模擬サムネイル転送時、40byte以下のバイナリはFROMに格納できたが、それを超えるとどこかのループに入り、EOFを1つずつ何個送っても、Bufferに入っていなかった。（Bufferに入れた直後にSendCharで返って来なかったため）
この原因をPC-Uart通信で探す必要がある

**Comment by reokashiyama** [comment]
OERRの可能性高
念のためFERRも必要？
![1528344530048](https://user-images.githubusercontent.com/31460945/41078193-302211ec-6a56-11e8-9da5-84fd094104bf.jpg)

**Comment by ryogaide** [comment]
このバグはOERRで確定。
CRENを再び1にすることで解決済み
